### ISSUE TITLE
Draw edge from child to parent

### ISSUE THREAD

**Issue by steveblue** [tbo47/dagre-es#25]
There was [an issue](https://github.com/dagrejs/dagre/issues/238 ) in the old repo raised because when drawing an edge from child to parent there is an error (or between any node and cluster), with a possible solution [here](https://github.com/dagrejs/dagre/pull/293). Would a PR be welcome integrating a fix into this project?

**Comment by tbo47** [comment]
yes, your PR is welcome. Sorry for the late answer.

**Comment by tbo47** [comment]
any update @steveblue 

or do I close this issue?

**Comment by steveblue** [comment]
We opted to go with Elk which supported this feature. Thank you though.
