### ISSUE TITLE
Align exports with dagre-d3

### ISSUE THREAD

**Issue by sidharthv96** [tbo47/dagre-es#5]
Hi,

We're trying to migrate mermaid-js from dagre-d3 to dagre-es, but ran into trouble because some members are not exported in dagre-es.

https://github.com/mermaid-js/mermaid/pull/3712#issuecomment-1298561298

Can we work together to expose the required items from dagre-es?

Thank you :)

**Comment by tbo47** [comment]
Sure, I will have a look.

**Comment by aloisklink** [comment]
I've manage to migrate the `mermaid` codebase from `dagre`/`dagre-d3` to `dagre-es`, and it looks like it has fixed a bunch of security warnings, and mermaid's bundle sizes seems to have gone down by ~200 KB (the magic of ESM!) See https://github.com/mermaid-js/mermaid/pull/3809/commits/d708ed8950b00fcfd707360165d0c183909584d2

Some of the exports were quite a bit different however, e.g. I had to do the following:

```js
// before
import dagreD3 from 'dagre-d3';
dagreD3.intersect.polygon(node, points, point);

// after
import { intersectPolygon } from 'dagre-d3-es/src/dagre-js/intersect/intersect-polygon';
intersectPolygon(node, points, point);
```

To be honest, the new syntax is probably better from an ESM/tree-shaking perspective though, and is probably the big reason why the built bundle has gone down by so much!

Many thanks for creating this fork!

**Comment by tbo47** [comment]
I answered in the other thread https://github.com/mermaid-js/mermaid/pull/3712

Don't hesitate to reopen this if needed.
